### ISSUE TITLE
Working through data instructions

### ISSUE THREAD

**Issue by jonkeane** [posit-conf-2023/arrow#2]
Using the instructions at https://posit-conf-2023.github.io/arrow/setup.html

I don't have an entirely fresh environment, but it's not been used too much for analysis either, so hopefully is semi representative of folk's setups.

- [x] https://posit-conf-2023.github.io/arrow/setup.html#nyc-taxi-data uses {here} be that is not requested to be installed anywhere. Same with {curl} though that was installed on my system already. 
- [x] when I tried the `open_dataset() ... write_dataset()` I get: `Error in attr(data, "tsp") <- c(start, end, frequency) :   object is not a matrix` I thought there was something about 13 and this, so maybe this is already known + fixed in 13 (I'm on 12 right now)
- [x] I was able to get the full nyc data using option 2 in about 40 minutes (on a 250 mb down connection)

One general note, it seemed a little bit odd to use `curl::multi_download()` in some places and then `download.file()` in others. Maybe an explanation of why?

FWIW, for the seattle library checkouts by title, `curl::multidownload()` was only a but faster:

```
   user  system elapsed 
 98.517 142.213 438.774 
```

compared to `download.file()` on the same file:
```
   user  system elapsed 
 68.629 150.350 592.596 
```

**Comment by stephhazlitt** [comment]
Thanks @jonkeane, excellent feedback. 

For `open_dataset()`, I don't think that is a `12.0.1` vs `13.0.0` issue, but IIRC you can get that strange error when you do't have `dplyr` loaded. Can you try this:

```
library(arrow)
library(dplyr)

data_path <- here::here("data/nyc-taxi") # Or set your own preferred path

open_dataset("s3://voltrondata-labs-datasets/nyc-taxi") |>
    filter(year %in% 2012:2021) |> 
    write_dataset(data_path, partitioning = c("year", "month"))
```
?

**Comment by jonkeane** [comment]
> For open_dataset(), I don't think that is a 12.0.1 vs 13.0.0 issue, but IIRC you can get that strange error when you do't have dplyr loaded. Can you try this: [...]

That does seem to be working now, yeah

**Comment by stephhazlitt** [comment]
Excellent point about the mish-mash of methods. Of course, the reason is either a good one (providing a couple of options for getting the big data _and_ one that uses `arrow`, so we can talk about using `arrow` with cloud) or not a good one (because that is the way R4DS gets the data 😆).

Any opinions on whether we:

- [ ] just mention out right we are using a mish mash of methods (we have 3 methods: `arrow::open_dataset()`, `curl::multidownload()` and `download.file()`)
- [ ] change the one optional `curl::multidownload()` one to `download.file()` (the Seattle CSV file) 
- [ ] change the various `download.file()` ones to `curl::multidownload()` (reduces to 2 methods)

?

**Comment by stephhazlitt** [comment]
> > For open_dataset(), I don't think that is a 12.0.1 vs 13.0.0 issue, but IIRC you can get that strange error when you do't have dplyr loaded. Can you try this: [...]
> 
> That does seem to be working now, yeah

OK, so I will add `library(dplyr)` in then&mdash;great catch.

**Comment by stephhazlitt** [comment]
FWIW, I have thought a number of times about opening an issue to see if a more informative error can be surfaced than `Error in attr(data, "tsp") <- c(start, end, frequency) :   object is not a matrix ` when you try and use some `arrow` functions and forget to load `dplyr`.

**Comment by jonkeane** [comment]
> Any opinions on whether we:
> 
> - just mention out right we are using a mish mash of methods (we have 3 methods: arrow::open_dataset(), curl::multidownload() and download.file())
> - change the one optional curl::multidownload() one to download.file() (the Seattle CSV file)
> - change the various download.file() ones to curl::multidownload() (reduces to 2 methods)

IMHO the second or third, maybe leaning towards the second since it's base and means you don't need to also ask folks to install curl (surely they will have it anyway, but still one less thing to need to on). but the third would reduce the number of variants in cases where they "aren't" "necessary"

**Comment by stephhazlitt** [comment]
Updating with feedback WIP: https://github.com/posit-conf-2023/arrow/pull/3

**Comment by thisisnic** [comment]
Closing this now as I just merged the PR, but let me know if we've missed anything.  Thanks for testing these out @jonkeane and making the updates @stephhazlitt !
